name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: social
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d social"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: social
      DB_USER: admin
      DB_PASSWORD: password
      IMAGE_ROOT: uploads

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (backend)
        working-directory: backend
        run: uv sync --frozen

      - name: Run tests (backend)
        working-directory: backend
        run: uv run pytest -q


  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/social-frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend/social-frontend
        run: npm ci

      - name: Run frontend unit tests (specs)
        working-directory: frontend/social-frontend
        run: npm test -- --watch=false

      - name: Build Angular app
        working-directory: frontend/social-frontend
        run: npm run build


  worker-check:
    name: Worker Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (worker)
        working-directory: worker
        run: uv sync --frozen

      - name: Run worker tests
        working-directory: worker
        run: uv run pytest -q
